### ISSUE TITLE
Automatic Repair?

### ISSUE THREAD

**Issue by Anjiang-Wei** [malusamayo/leakage-analysis#2]
After detecting the leakage, can your tool automatically suggest a fix to the users?

**Comment by malusamayo** [comment]
For some forms of leakage (e.g., pre-processing leakage), automatically transforming code based on best practices is definitely possible and not too hard to implement. There could be some future work in this direction :)

**Comment by zainebmb** [comment]
when building the docker image it stops because  the command npm install --g lerna failed to complete successfully.

![image](https://user-images.githubusercontent.com/58008680/234935308-ddebb884-bd07-439a-8ab1-0e5e26ae0d26.png)

I made sure that It's not because of my network connection nor because of missing docker permissions.

any assistance on how to solve this issue please?

**Comment by malusamayo** [comment]
@zainebmb Seems that the latest version of the `lerna` package is no longer compatible. 
Replace the line in Dockerfile with `RUN npm install --g lerna@4.0.0` and rebuild the docker image -- things should work again.
